HTTP_OK=200
HTTP_BAD_REQUEST=400
HTTP_UNAUTHORIZED=401
HTTP_NOT_FOUND=404
HTTP_TEMPORARY_REDIRECT=307

STR_HTTP_ERROR={
    HTTP_OK: "OK",
    HTTP_UNAUTHORIZED: "Unauthorized",
    HTTP_BAD_REQUEST: "Bad request",
    HTTP_NOT_FOUND: "Not Found",
    HTTP_TEMPORARY_REDIRECT: "Temporary redirect"
}
#App error
UNKNOWWN=-1
OK=0
COMMAND_NOT_FOUND=1
ERROR_HTTP=2
BAD_SESSION=3
ID_NOT_FOUND=4
MALFORMED_REQUEST=5
NOT_AUTHORIZED=6
FILE_NOT_FOUND=7